In [ ]:
 ## For google colab only
from google.colab import drive
drive.mount('/content/drive')

## on Phuc's drive
%cd /content/drive/MyDrive/Uni/Thesis

Mounted at /content/drive
/content/drive/MyDrive/Uni/Thesis

In [ ]:
detectDS_link = '/content/drive/MyDrive/Uni/Thesis/dataset/detection'
# classifyDS_link = '/content/drive/MyDrive/Uni/Thesis/dataset/classification'
# In detection folder
dtecDS_info = "/content/drive/MyDrive/Uni/Thesis/dataset/detection/PasadenaUrbanTrees/detection_datasets.json"
#clsDS_info = "/content/drive/MyDrive/Uni/Thesis/dataset/detection/PasadenaUrbanTrees/classification_datasets.json"
rois_info =  "/content/drive/MyDrive/Uni/Thesis/dataset/detection/PasadenaUrbanTrees/rois.json"
pano_info = "/content/drive/MyDrive/Uni/Thesis/dataset/detection/PasadenaUrbanTrees/panos.json"

In [ ]:
import pandas as pd
import json
from pandas.io.json import json_normalize

with open(dtecDS_info) as json_data:
  data = json.load(json_data)

In [ ]:
def getDtecDFInfo(ds):
    dsX = pd.DataFrame(list(ds['extended']))
    df = pd.concat([ds,dsX], axis=1)
    # df = df.drop(['Longitude','Latitude','extended'], axis=1)

    return df

In [ ]:
dtecDF_Itrain, dtecDF_Itest, dtecDF_Ival = [getDtecDFInfo(pd.DataFrame(data[x])) for x in ('train', 'test', 'val')]

In [ ]:
print(dtecDF_Itrain.columns.values)

['roi' 'extended' 'class_id' 'bad' 'lat' 'diff' 'lng' 'trunk_id'
 'train_val_test' 'Street_Direction' 'OBJECTID' 'House_Number'
 'Street_Name' 'Longitude' 'Latitude' 'Trunk_Diameter' 'Street_Type'
 'Common_Name' 'Genus' 'Species' 'Street_Suffix']

In [ ]:
dtecDF_Itrain = dtecDF_Itrain.drop(['Street_Type','Common_Name','Genus','Species','Street_Suffix','Longitude','Latitude','extended'], axis=1)
dtecDF_Itrain

,roi,class_id,bad,lat,diff,lng,trunk_id,train_val_test,Street_Direction,OBJECTID,House_Number,Street_Name,Trunk_Diameter
0,ROI10,0.0,False,34.146522,False,-118.147762,0.0,NaN,N,1019,37,ARROYO,13
1,ROI10,0.0,False,34.146634,False,-118.147764,1.0,NaN,N,1020,41,ARROYO,15
2,ROI10,0.0,False,34.146562,False,-118.147549,2.0,NaN,E,1021,177,COLORADO,19
3,ROI10,0.0,False,34.147326,False,-118.147779,4.0,NaN,N,1024,95,ARROYO,14
4,ROI10,NaN,True,34.147364,True,-118.147881,NaN,NaN,N,1025,95,ARROYO,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
18180,ROI11,NaN,False,34.130466,True,-118.138332,NaN,NaN,S,76749,895,MADISON,4
18181,ROI11,NaN,False,34.133119,True,-118.138208,NaN,NaN,S,76750,736,MADISON,1
18182,ROI12,14.0,False,34.145774,False,-118.135513,4.0,NaN,E,76751,716,COLORADO,14
18183,ROI12,NaN,False,34.145780,True,-118.135432,NaN,NaN,E,76752,716,COLORADO,3
18184,ROI12,14.0,False,34.145787,False,-118.134182,0.0,NaN,E,76753,790,COLORADO,13

In [ ]:
""" 
ROI json
"""
with open(rois_info) as json_data:
  roiData = json.load(json_data)

roiDF = pd.DataFrame(roiData)
roiDF

                                                 roi  train_val_test   name
0   [34.160618, -118.136974, 34.151917, -118.124386]               0   ROI4
1   [34.161419, -118.119898, 34.151917, -118.106368]               0   ROI5
2     [34.17143, -118.136974, 34.16143, -118.124386]               0   ROI6
3     [34.17143, -118.119898, 34.16143, -118.106368]               0   ROI7
4        [34.160618, -118.1496, 34.151604, -118.137]               0   ROI8
5          [34.17143, -118.1496, 34.16143, -118.137]               0   ROI9
6        [34.150975, -118.1496, 34.140975, -118.137]               0  ROI10
7            [34.1403, -118.1496, 34.1303, -118.137]               0  ROI11
8   [34.150975, -118.136974, 34.140975, -118.124386]               0  ROI12
9       [34.1403, -118.136974, 34.1303, -118.124386]               1  ROI13
10    [34.150975, -118.1243, 34.140975, -118.106368]               2  ROI14
11        [34.1403, -118.1243, 34.1303, -118.106368]               2  ROI15
12          [34.1403, -118.1624, 34.1303, -118.1498]               2  ROI16
13      [34.150975, -118.1624, 34.140975, -118.1498]               2  ROI17
14      [34.160618, -118.1624, 34.151604, -118.1498]               2  ROI18
15        [34.17143, -118.1624, 34.16143, -118.1498]               2  ROI19

In [ ]:
""" 
pano json
"""
with open(pano_info) as json_data:
  panoData = json.load(json_data)

panoDF = pd.DataFrame(panoData)
panoKeys = list(panoData.keys())
panoVlue = list(panoData.values())

panoDF_Id, panoDF_Ip, panoDF_Ilk, panoDF_Iln = [pd.DataFrame(list(pd.DataFrame(panoVlue)[x])) for x in ('Data', 'Projection', 'Links','Location')]
panoDF = pd.concat([panoDF_Id, panoDF_Ip, panoDF_Iln], axis=1).drop(['copyright','country','region', 'image_date', 'imagery_type'], axis=1)
panoDF

,tile_height,image_width,image_height,tile_width,pano_yaw_deg,tilt_yaw_deg,projection_type,tilt_pitch_deg,elevation_wgs84_m,panoId,description,elevation_egm96_m,zoomLevels,original_lng,original_lat,lat,lng
0,512,13312,6656,512,89.24,23.66,spherical,1.82,227.070125,RSW7f_FU5E17LTwSY7kRoA,Locust St,261.010712,5,-118.131954,34.150503,34.150501,-118.132004
1,512,13312,6656,512,85.74,56.74,spherical,2.19,218.571702,EacCv-N9UOtvzwAlOmVvkg,,252.465973,5,-118.119060,34.151960,34.151961,-118.119080
2,512,13312,6656,512,180.31,6.42,spherical,1.96,262.388395,-nkfx7Yp4NUrYjOtYgUcAw,N Sierra Bonita Ave,296.220581,5,-118.117845,34.164713,34.164713,-118.117793
3,512,13312,6656,512,0.21,88.62,spherical,2.92,215.605096,Kc2ejT4GY8c1Q_tx62_bQg,S Hudson Ave,249.583237,5,-118.133907,34.143693,34.143622,-118.133858
4,512,13312,6656,512,1.29,-77.16,spherical,2.53,179.086640,qaEHkXvs9LH3x-5Ll0_kAQ,San Marino Ave,213.024033,5,-118.108501,34.135324,34.135324,-118.108502
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36205,512,13312,6656,512,268.68,-179.55,spherical,1.07,222.178857,zmAhjEVCNDtdlbLkbQGPFQ,I-210,256.064453,5,-118.117157,34.152577,34.152531,-118.117156
36206,512,13312,6656,512,265.89,118.34,spherical,0.55,222.856515,9dajUATLhZxSkjTuzmmyvQ,I-210,256.760712,5,-118.123025,34.152446,34.152399,-118.123019
36207,512,13312,6656,512,88.73,-11.16,spherical,2.17,239.586037,qrsFAynK2E1tLoEdlJHjTA,E Villa St,273.539764,5,-118.141807,34.154170,34.154190,-118.141807
36208,512,13312,6656,512,89.91,0.11,spherical,3.57,280.678552,bXiXQWuMgnulkMfJ4tT8Kw,E Washington Blvd,314.491730,5,-118.118180,34.169091,34.169096,-118.118188
36209,512,13312,6656,512,358.89,-42.41,spherical,1.42,227.145527,nkdrm7KoUZ6y0j8KEz4tgw,N El Molino Ave,261.094513,5,-118.136906,34.151963,34.151972,-118.136903

In [ ]:
panoDF_Ilk[0]

,0,1,2,3,4,5,6
0,"{'yawDeg': '269.5', 'road_argb': '0x80fdf872',...","{'yawDeg': '89.89', 'road_argb': '0x80fdf872',...",None,None,None,None,None
1,"{'yawDeg': '266.25', 'road_argb': '0x80fdf872'...","{'yawDeg': '86.25', 'road_argb': '0x80fdf872',...",None,None,None,None,None
2,"{'yawDeg': '359.89', 'road_argb': '0x80fdf872'...","{'yawDeg': '179.89', 'road_argb': '0x80fdf872'...",None,None,None,None,None
3,"{'yawDeg': '179.52', 'road_argb': '0x80fdf872'...","{'yawDeg': '359.52', 'road_argb': '0x80fdf872'...",None,None,None,None,None
4,"{'yawDeg': '180.07', 'road_argb': '0x80fdf872'...","{'yawDeg': '0.07', 'road_argb': '0x80fdf872', ...",None,None,None,None,None
...,...,...,...,...,...,...,...
36205,"{'yawDeg': '88.32', 'road_argb': '0x80fdf872',...","{'yawDeg': '268.32', 'road_argb': '0x80fdf872'...",None,None,None,None,None
36206,"{'yawDeg': '84.46', 'road_argb': '0x80fdf872',...","{'yawDeg': '264.45', 'road_argb': '0x80fdf872'...",None,None,None,None,None
36207,"{'yawDeg': '269.73', 'road_argb': '0x80fdf872'...","{'yawDeg': '89.73', 'road_argb': '0x80fdf872',...",None,None,None,None,None
36208,"{'yawDeg': '270.05', 'road_argb': '0x80fdf872'...","{'yawDeg': '90.05', 'road_argb': '0x80fdf872',...",None,None,None,None,None
36209,"{'yawDeg': '179.54', 'road_argb': '0x80fdf872'...","{'yawDeg': '359.73', 'road_argb': '0x80fdf872'...",None,None,None,None,None

In [ ]:
print(panoDF.columns.values)

['tile_height' 'image_width' 'image_height' 'tile_width' 'pano_yaw_deg'
 'tilt_yaw_deg' 'projection_type' 'tilt_pitch_deg' 'elevation_wgs84_m'
 'panoId' 'description' 'elevation_egm96_m' 'zoomLevels' 'original_lng'
 'original_lat' 'lat' 'lng']

In [ ]:
import matplotlib.pyplot as plt
import matplotlib.image as mpimg

imgT = mpimg.imread('/content/drive/MyDrive/Uni/Thesis/dataset/detection/PasadenaUrbanTrees/streetview/qaEHkXvs9LH3x-5Ll0_kAQ_z2.jpg')
plt.imshow(imgT)

OSError: ignored